version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: smallauth-postgres
    environment:
      POSTGRES_DB: smallauth
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
